### ISSUE TITLE
MAMP

### ISSUE THREAD

**Issue by teklynk** [teklynk/portfolioCMS#1]
Issue with log in when installing to MAMP server. Still researching this issue. Could be related to the version of PHP and/or MySQL.

**Comment by Emanuele20** [comment]
Trying to update ur mysql syntax to mysqli or better pdo any suggestion? Could be an idea or just waste my time? Any suggestion r welcome!
Kindly regards
Emanuele

**Comment by teklynk** [comment]
I have updated the code to use MySQLi.
