### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by naimjeem** [teklynk/portfolioCMS#3]
custom image upload not working.

**Comment by teklynk** [comment]
Please verify your permissions for the uploads folder.

**Comment by Emanuele20** [comment]
Hi! Sorry for this....but ur work is awesome! Just a simple question...ur core works in mysql syntax or mysqli or pdo? What I'd like to know if is sure versus sql-injection...thx!

**Comment by teklynk** [comment]
The portfoliocms project is not perfect. I am sure there are security holes
and things that I missed. Please take the code and make it your own.

You may want to look into sanitizing like this. filter_var($data['title'],
FILTER_SANITIZE_STRING)
Or escaping strings like this. mysql_real_escape_string($user)

**Comment by Emanuele20** [comment]
Really thx again for ur answer and maybe i'd like to try to rewrite in mysqli i'm looking that is in mysql syntax...any suggestion from where i ve to start? Thx again and if i ve success i will send ur code updated)
